// <auto-generated />
namespace EFWeb.core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateDegreeMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDegreeMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202203100706006_updateDegreeMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
